### PR TITLE
Fix to solve Jenkins issue 66721

### PR DESCRIPTION
**Pull request by Andre-K42**
https://issues.jenkins.io/browse/JENKINS-66721

### CODE REVIEW

**Comment by misery** [comment]
You should post that change to https://reviews.reviewboard.org/ :-)

**Comment by misery** [comment]
@davidt Ping! Could this be merged?

**Comment by misery** [comment]
@chipx86 Hi, is it possible to merge this?

**Comment by davidt** [comment]
Andre,

Sorry about the delay here. We've been pretty busy with 5.0 beta prep. I'll get this merged tomorrow.

**Comment by misery** [comment]
@davidt @chipx86
Thanks for merge! Could you release a new version, too?

**Comment by misery** [comment]
@davidt @chipx86 ... ping? Could you release it?

**Comment by davidt** [comment]
Andre,

Sorry for the delay. It took some doing to fix up the CD workflow due to some infrastructure changes on the Jenkins side. The release is here: https://github.com/jenkinsci/rb-plugin/releases/tag/1.4, and I believe it should get published to plugins.jenkins.io soon.

**Pull request merged**
